// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import path from "path";
import fs from "fs";

const envPath = path.join(process.cwd(), ".env.local");
console.log("Loading Prisma config...");
console.log("CWD:", process.cwd());
console.log("Env path:", envPath);
console.log("Env file exists:", fs.existsSync(envPath));

config({ path: envPath });

import { defineConfig } from "prisma/config";

console.log("DATABASE_URL:", process.env.DATABASE_URL ? "SET" : "NOT SET");
console.log("POSTGRES_URL:", process.env.POSTGRES_URL ? "SET" : "NOT SET");

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] || process.env["POSTGRES_URL"] || process.env["POSTGRES_PRISMA_URL"],
  },
});
